name: webclient
description: Daily Fantasy Soccer
dependencies:
    angular: '>=0.11.0 <0.12.0'
    browser: '>=0.10.0 <0.11.0'
    json_object: 1.0.18+2
    web_components: '>=0.3.3 <0.4.0'
    
dev_dependencies:
    unittest: any
  
transformers:
- angular:
    html_files:
    - web/view/lobby.tpl.html
    - web/view/live_contests.tpl.html
    - web/view/entered_contests.tpl.html
    - web/view/home.tpl.html
    - web/view/join.tpl.html
    - web/view/login.tpl.html
    - web/view/enter_contest.tpl.html
- $dart2js:
    checked: false
    minify: false
    verbose: false
    analyzeAll: false
    suppressWarnings: false
    suppressHints: false
    terse: false