name: webclient
description: Epic Eleven
dependencies:
  angular: '>=1.0.0 <1.1.0'
  browser: '>=0.10.0 <0.11.0'
dev_dependencies:
  unittest: any

transformers:
- angular

- $dart2js:
    checked: false
    minify: true
    verbose: true
    analyzeAll: false
    commandLineOptions: [ --show-package-warnings ] #, --dump-info]
    suppressWarnings: false
    suppressHints: false
    terse: true
    csp: false