name: webclient
description: Epic Eleven
dependencies:
  angular2: any
  barback: '>=0.13.0 <0.15.3'
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: ^1.0.2
  http: ^0.11.0
  scroll: any
  stream_transformers: ^0.3.0
dev_dependencies:
  unittest: any
transformers:
- webclient/transformer_less
- angular2:
    platform_directives:
    - package:angular2/common.dart#COMMON_DIRECTIVES
    platform_pipes:
    - package:angular2/common.dart#COMMON_PIPES
    - package:angular2/common.dart#COMMON_PIPES
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: package:http/browser_client.dart
      Client: package:http/http.dart
- dart_to_js_script_rewriter
