name: webclient
description: Epic Eleven
dependencies:
  angular: "^1.1.2+2"
  barback: '>=0.13.0 <0.15.3'
  browser: '>=0.10.0 <0.11.0'
  scroll: any
dev_dependencies:
  unittest: any
transformers:
- angular
- webclient/transformer_main:
    $include: web/index.html
- webclient/transformer_less
- $dart2js:
    checked: false
    csp: false
    minify: true
    suppressHints: false
    suppressWarnings: false
    terse: true
    verbose: true
