name: webclient
description: Daily Fantasy Soccer
dependencies:
    angular: '>=0.13.0 <0.14.0'
    browser: '>=0.10.0 <0.11.0'
    json_object: 1.0.18+2
        
dev_dependencies:
    unittest: any
  
transformers:
- angular:
    html_files:
    - web/view/join.tpl.html    
    - web/view/lobby.tpl.html
    - web/view/login.tpl.html
    - web/view/enter_contest.tpl.html
    - web/view/view_contest.tpl.html
