name: webclient
description: Daily Fantasy Soccer
dependencies:
    angular: '>=0.12.0 <0.13.0'
    browser: '>=0.10.0 <0.11.0'
    json_object: 1.0.18+2
    web_components: '>=0.3.3 <0.4.0'
    
dev_dependencies:
    unittest: any
  
transformers:
- angular:
    html_files:
    - web/view/join.tpl.html    
    - web/view/lobby.tpl.html
    - web/view/login.tpl.html
    - web/view/enter_contest.tpl.html