name: webclient
description: Daily Fantasy Soccer
dependencies:
    angular: '>=0.11.0 < 0.12.0'
    angular_dart_ui_bootstrap: 0.2.1
    browser: '>=0.10.0 < 0.11.0'
    bootjack: 0.6.5
    json_object: 1.0.18+2
    
dev_dependencies:
    unittest: 0.10.1+2
  
transformers:
- angular:
    html_files:
    - web/view/contest_entry.tpl.html
    - web/view/home.tpl.html
    - web/view/join.tpl.html
    - web/view/lobby.tpl.html
    - web/view/login.tpl.html
- $dart2js:
    checked: false
    minify: true
    verbose: true
    analyzeAll: false
    suppressWarnings: false
    suppressHints: false
    terse: false